[theme]
# A vibrant, hot pink for interactive elements
primaryColor = "#F62681"

# A deep, dark purple for the main background
backgroundColor = "#241B2F"

# A slightly lighter purple for the sidebar
secondaryBackgroundColor = "#3E2C41"

# A soft, off-white for clear text readability
textColor = "#E2E1E5"

font = "sans serif"